name: openapi_model_cli
description: A sample command-line application.
version: 1.0.0
homepage: https://www.moinsen.dev

# This allows us to use openapi2model_cli on itself during development.
executables:
  openapi2model_cli: openapi2model_cli_dev

environment:
  sdk: '>=2.16.0 <3.0.0'


dependencies:
  path: ^1.8.0
  args: ^2.3.0
  yaml: ^3.1.0
  mustache_template: ^2.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
