name: openapi_model_cli
description: A sample command-line application.
version: 0.0.0
homepage: https://www.moinsen.dev

executables:
  openapi2model_cli:

environment:
  sdk: '>=2.16.0 <3.0.0'


dependencies:
  path: ^1.8.0
  args: ^2.3.0
  yaml: ^3.1.0
  mustache_template: ^2.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

