name: example_api
description: A new api model model package.
version: 0.0.1
homepage: https://www.example.com

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  freezed_annotation: ^1.1.0
  json_serializable: ^6.1.4
  json_annotation: ^4.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.7
  freezed: ^1.1.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
